### ISSUE TITLE
Can only download English patch

### ISSUE THREAD

**Issue by Iroboke** [ObserverOfTime/WA2EnglishPatch#10] opened 2022-03-12 18:19 UTC
### Description

I thought I had all the necessary files. What is going wrong?
![Screenshot (3)](https://user-images.githubusercontent.com/101474066/158029517-be6f6985-16d1-4b46-86ae-7f257ad2f6f2.png)
![Screenshot (4)](https://user-images.githubusercontent.com/101474066/158029524-cb5dd326-ae53-4b74-8b56-a1755c72b3ff.png)
![Screenshot (5)](https://user-images.githubusercontent.com/101474066/158029530-3f107277-5a7f-4b20-a719-c4fd88baea82.png)

### Steps to Reproduce

1. Open WA2_patch.exe
2. Accept agreement 
3. Next
4. Browse Downloads\WHITE ALBUM2 folder
5. Next
6. Custom installation
7. Check audio-only subs and Subbed videos
8. Next
9. Next
10. Install 
11.  Download failed: 404 Not Found

**Comment by ObserverOfTime** [comment] 2022-03-12 19:32
Duplicate of #8

**Closed as completed by ObserverOfTime** 2022-03-12 19:32 UTC
Labels: duplicate

**Comment by Iroboke** [comment] 2022-03-12 21:54
I already downloaded the files mentioned in #6. I'm still getting the error
message.

**Comment by 1h5w** [comment] 2022-03-13 07:10
> I already downloaded the files mentioned in #6. I'm still getting the error message.

You need to manually copy the downloaded files into the game folder.
